# Generated by Django 5.2.8 on 2025-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 5 Bedroom Duplex in GRA Phase 2', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('price', models.CharField(help_text='e.g. ₦350 Million or ₦2.5M per plot', max_length=50)),
                ('location', models.CharField(help_text='e.g. GRA Phase 2, Port Harcourt', max_length=200)),
                ('details', models.TextField(help_text='Short description of the property')),
                ('image', models.ImageField(help_text='Main photo', upload_to='properties/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-date_added'],
            },
        ),
    ]
